SPOOL CreateTableSpool.txt

CREATE TABLE MEMBER
(
SSN NUMBER,
NAME VARCHAR2(50),
HOME_ADDRESS VARCHAR2(1000),
CAMPUS_ADDRESS VARCHAR2(1000),
PHONE_NO VARCHAR2(50),
MEMBER_TYPE VARCHAR2(50),
GRACE_PERIOD NUMBER,
BORROW_PERIOD NUMBER, 
EMPLOYEE_TYPE VARCHAR(50),
STAFF_TYPE VARCHAR(50),
PRIMARY KEY(SSN)
);


CREATE TABLE CARD
(
CARD_ID NUMBER,
PHOTO BLOB,
ISSUE_DATE DATE,
EXPIRY_DATE DATE,
VALIDITY DATE,
M_SSN NUMBER,
PRIMARY KEY (CARD_ID),
FOREIGN KEY (M_SSN) REFERENCES MEMBER(SSN) ON DELETE CASCADE
);



CREATE TABLE BOOK
(
ISBN NUMBER,
TITLE VARCHAR2(100),
BINDING VARCHAR2(20),
LANGUAGE VARCHAR2(100),
EDITION VARCHAR2(30),
AUTHOR VARCHAR2(50),
DESCRIPTION CLOB,
VOLUME VARCHAR2(30),
SUBJECT_AREA VARCHAR2(100),
BOOK_TYPE VARCHAR2(30), /*'Map', 'Reference books', 'Rare books'*/
AVAILABILITY CHAR(1) NOT NULL ENABLE CHECK(AVAILABILITY IN('Y', 'N')),
STATUS_TYPE VARCHAR2(30),/*'Lent', 'Unloanable', 'Acquire'*/
PRIMARY KEY(ISBN)
);

CREATE TABLE COPY( 
BOOK_ID NUMBER, 
ISBN NUMBER NOT NULL, 
STATUS VARCHAR2(20), 
PRIMARY KEY(BOOK_ID),
FOREIGN KEY(ISBN) REFERENCES BOOK(ISBN) ON DELETE CASCADE
); 

CREATE TABLE BORROW
(
BOOK_ID NUMBER,
M_SSN NUMBER,
ISSUED_BY NUMBER,
ISSUE_DATE DATE,
DUE_DATE DATE,
RETURN_DATE DATE,
GRACE_PERIOD DATE,
STATUS VARCHAR2(20),
PRIMARY KEY(BOOK_ID,M_SSN,ISSUE_DATE),
FOREIGN KEY(BOOK_ID) REFERENCES COPY(BOOK_ID),
FOREIGN KEY(M_SSN) REFERENCES MEMBER(SSN),
FOREIGN KEY(ISSUED_BY) REFERENCES MEMBER(SSN)
);


CREATE TABLE VISITS
(
M_SSN NUMBER,
CHECK_IN DATE,
CHECK_OUT DATE,
NAME VARCHAR2(50),
PASS_ID NUMBER,
VISITOR_TYPE VARCHAR2(50), /*Member, Relative, Guest*/
VALIDITY_DATE DATE,
PRIMARY KEY (M_SSN,CHECK_IN),
FOREIGN KEY (M_SSN)REFERENCES MEMBER(SSN)
);

SPOOL OFF;